require:
  - rubocop-rails

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

HasAndBelongsToMany:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Naming/AccessorMethodName:
  Enabled: false

AllCops:
  Include:
    - 'app/**/*.rb'